[package]
name = "arpg_take2"
version = "0.1.0"
authors = ["Dylan Halperin <dylan@dylemma.io>"]

[dependencies]
bytes = "0.4"
futures = "0.1"
rand = "0.3"
serde = "1.0"
serde_derive = "1.0"
tokio-io = "0.1"
tokio-core = "0.1"
tokio-proto = "0.1"
tokio-serde = "0.1"
tokio-serde-bincode = "0.1"